Update README.md
bmstu-iu8-cpp-sem-3/lab-05-stack pull request #1
Opened 2018-10-03 20:23 UTC by rusdevops

2018-10-03 20:58 UTC, drewxa commented on README.md
> +Реализовать **unit-test**'ы с использованием `gtest` для реализованных шаблонов в заданиях 1 и 2.
почему gtest выделен через ` ?

2018-10-03 21:05 UTC, drewxa requested changes

2018-10-03 21:05 UTC, drewxa commented on README.md
> +Реализовать некопируемый перемещаемый шаблон класса **stack** с методами `pop`, `push`, `top`.
я тут понял, что компилятор не сможет разрезолвить класс. нужно
```cpp
void push(T&& value);
```
поправь, плз

2018-10-04 21:44 UTC, rusdevops commented on README.md
> +Реализовать некопируемый перемещаемый шаблон класса **stack** с методами `pop`, `push`, `top`.
Fixed

2018-10-05 20:19 UTC, drewxa requested changes

2018-10-05 20:19 UTC, drewxa commented on README.md
> +  void push(T&& value);
```cpp
void push(const T& value);
void push(T&& value);
```

2018-10-06 18:52 UTC, merged